name: DVHSiegeCore
version: '$version'
main: com.danvhae.minecraft.siege.core.DVHSiegeCore
api-version: 1.12.2
authors: [해야, 보라비, 단츄, 만현덕, 로미오는줄리엣]
description: 꿈뻑 공성전 콘텐츠 데이터 등 핵심 제어 플러그인
website: https://cafe.naver.com

depend: [WorldEdit, WorldGuard, Vault]

commands:
  회의실:
    permission: siegecontrol.player
    description: 회의실로 이동합니다

  castle-data:
    description: 별 데이터 제어 명령어
  player-data:
    description: 공성 플레이어 관리 명령어
  gui-data:
    description: gui데이터 관리 명령어

  siege-team-data:
    description: team data handling
    
  master-config:
    description: 각종 설정 제어 명령어

  멸망판정:
    description: 별 멸망 판정을 위한 npc 명령어
permissions:
  siegecontrol.support:
    default: false
    description: 본 콘텐츠 지원팀에게 부여됩니다
  siegecontrol.player:
    default: true
    description: 대기 중인 일꾼만이 이 권한을 가지고 있지 않습니다.